# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt
#
# Tell Travis what to do
# https://travis-ci.com/nedbat/coveragepy

dist: xenial
language: python

cache: pip
matrix:
  include:
    - arch: arm64
      python: 2.7
    - arch: amd64
      python: 2.7
    - arch: arm64
      python: 3.5
    - arch: amd64
      python: 3.5
    - arch: arm64
      python: 3.6
    - arch: amd64
      python: 3.6
    - arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - arch: arm64
      python: 3.8
    - arch: amd64
      python: 3.8
    - arch: amd64
      python: pypy2.7-6.0
    - arch: amd64
      python: pypy3.5-6.0
      # Skipping for Arm64, pypy has aarch64 support - but it isn't released yet.

env:
  matrix:
    - COVERAGE_COVERAGE=no
    - COVERAGE_COVERAGE=yes

install:
  - pip install -r requirements/ci.pip
  - pip freeze

script:
  - tox

after_script:
  - |
    if [[ $COVERAGE_COVERAGE == 'yes' ]]; then
      python igor.py combine_html
      pip install codecov
      codecov -X gcov --file coverage.xml
    fi
